export const Data7 = [
    {
        school: '希望小学',
        grade: '一年级',
        class: '一班',
        name: '张三',
        scoreMath: 'A',
        scoreChina: 'A',
        scoreEnglish: 'A',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '一班',
        name: '李四',
        scoreMath: 'B',
        scoreChina: 'B',
        scoreEnglish: 'C',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '一班',
        name: '王五',
        scoreMath: 'A',
        scoreChina: 'C',
        scoreEnglish: 'B',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '一班',
        name: '赵六',
        scoreMath: 'B',
        scoreChina: 'C',
        scoreEnglish: 'C',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '二班',
        name: '张三丰',
        scoreMath: 'B',
        scoreChina: 'B',
        scoreEnglish: 'B',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '二班',
        name: '李四娘',
        scoreMath: 'A',
        scoreChina: 'C',
        scoreEnglish: 'B',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '二班',
        name: '王五六',
        scoreMath: 'A',
        scoreChina: 'B',
        scoreEnglish: 'C',
    },
    {
        school: '希望小学',
        grade: '一年级',
        class: '二班',
        name: '赵六子',
        scoreMath: 'A',
        scoreChina: 'C',
        scoreEnglish: 'A',
    },
]
